package com.preetanshumishra.FinBossAndroid

import android.app.Application
import com.preetanshumishra.FinBossAndroid.di.AppDependencies
import com.preetanshumishra.FinBossAndroid.di.DaggerAppComponent
import com.preetanshumishra.FinBossAndroid.di.initializeAppDependencies

/**
 * FinBossApplication is the Application class for the FinBoss Android app.
 *
 * What is Application?
 * - It's called once when the app starts, before any activities are created
 * - It's a good place to initialize global resources like Dagger
 * - It has a lifecycle tied to the entire app process
 *
 * What does Dagger do here?
 * 1. DaggerAppComponent.builder() - Creates a builder for our AppComponent
 * 2. .context(this) - Provides the Application context to Dagger
 * 3. .build() - Generates and builds the entire dependency graph
 * 4. AppDependencies(...) - Wraps the component in an easy-to-access container
 * 5. initializeAppDependencies(...) - Stores it globally so we can access it from anywhere
 */
class FinBossApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        // ===== Step 1: Build the Dagger component =====
        // DaggerAppComponent is generated by Dagger at compile time
        // It has a builder that requires a Context
        val appComponent = DaggerAppComponent
            .builder()
            .context(this)
            .build()

        // ===== Step 2: Create the dependencies container =====
        // This wraps the component and exposes only what we need
        val appDependencies = AppDependencies(appComponent)

        // ===== Step 3: Initialize the global reference =====
        // Now we can access dependencies from anywhere with: appDependencies.authService
        initializeAppDependencies(appDependencies)
    }
}
